#!/bin/bash

set -euo pipefail

echo "+++ Installing java7-sdk"
# "java7-sdk" is a virtual package provided by:
# openjdk-7-jdk default-jdk
# You must choose one to install.
sudo aptitude install -y openjdk-7-jdk
