#!/bin/bash

set -ueo pipefail

tools_version=${BK_SDK_VERSION}

echo "+++ Downloading SDK Tools package (${tools_version})"
curl --silent -O http://dl.google.com/android/android-sdk_${tools_version}.tgz
tar xf android-sdk_${tools_version}.tgz
cd android-sdk-linux/
ls -larth
